components:
  applications:
    entity: component
    title: Applications
  applications.companies:
    repository: aeroclub.companies
    title: Companies & Profiles Console
    entity: component
    project: Aeroclub Companies
    description: Консоль для настроек компаний
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=18580224
    technologies:
    links:
  applications.passport:
    repository: aeroclub.passport
    title: Passport
    entity: component
    type: Изменить
    project: Aeroclub Passport
    description: Предоставление данных для доступа к ресурсам
    url: http://wiki.aeroclub.int/display/PROJECTDOC/Passport
    technologies:
    links:
      - id: db.passport
  applications.time:
    repository: aeroclub.time
    title: Time
    entity: component
    project: Aeroclub Time
    description: Самостоятельное оформления услуг клиентами
    url: http://wiki.aeroclub.int/display/PROJECTDOC/Time
    technologies:
    links:
      - id: applications.travelboard
        direction: <-->
  applications.time.backend:
    repository: aeroclub.time.backend
    title: Time Backend
    entity: component
    type: Удалить
    project: Aeroclub Time
    description:
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Time.Api
    technologies:
    links:
      - id: db.cabinet
        direction: -->
        title: тест
      - id: services.authfx
        direction: -->
      - id: services.propertyfx
        direction: -->
      - id: services.businesstrips
        direction: -->
      - id: services.journeys
        direction: -->
      - id: services.budgeting
        direction: -->
      - id: applications.passport
        direction: -->
      - id: services.wscommon
        direction: -->
      - id: services.time_stateengine
        direction: -->
      - id: applications.travelboard.frontend
        direction: <-->
      - id: db.profiles
        direction: -->
      - id: services.dictionaries
        direction: -->
      - id: services.vault
        direction: -->
      - id: backgroundservices.indexer
        direction: -->
  applications.newtime:
    repository: aeroclub.time.ui
    title: NewTime
    entity: component
    project: Aeroclub Time
    description: Веб-приложение на React
    url: http://wiki.aeroclub.int/display/PROJECTDOC/Travelboard
    technologies:
    links:
      - id: applications.time
        direction: <-->
        title: Переход на страницы старого Тайма
      - id: services.inappstory
        direction: -->
        title: Получение историй и онбординга
      - id: services.timeApi
        direction: -->
        title: Вся основная работа с виджетами, командировками
  applications.dictionaries:
    repository: aeroclub.platform.dictionaries
    title: Dictionaries Console
    entity: component
    project: Aeroclub Platform
    description:
    url:
    technologies:
