components:
  services:
    title: Services
    entity: component
  services.aeroclubApi:
    repository: aeroclub.services.api
    title: AeroclubApi
    entity: component
    project: Aeroclub Services
    description: Работа с мобильным приложением Link
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=18580096
    technologies:
    links:
      - id: services.aeroclubApiQuery
        direction: -->
        title: Получение информации
  services.aeroclubApiQuery:
    repository: aeroclub.services.api.query
    title: AeroclubApiQuery
    entity: component
    project: Aeroclub Services
    description: Используется для получения специфичной информации о заказах, командировках, проездных документах и пр. из базы Cabinet
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Mobile+Api+Query
    technologies:
    links:
      - id: db.cabinet
        direction: -->
  services.businesstrips:
    repository: aeroclub.services.businesstrips
    title: BusinessTrips
    entity: component
    project: Aeroclub Services
    description: Создан для агрегации бизнес-логики из области командировок, на первом этапе реализует импорт командировок из внешних систем
    url: http://wiki.aeroclub.int/display/PROJECTDOC/BusinessTrips+Service
    technologies:
    links:
      - id: db.cabinet
        direction: -->
  services.companies:
    repository: aeroclub.services.companies
    title: Companies
    entity: component
    project: Aeroclub Services
    description: REST cервис предназначен для работы с профайлами компаний
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=19141737
    technologies:
    links:
      - id: db.companies
        direction: -->
  services.pricingscheme:
    repository: aeroclub.services.companiesws.v2
    title: PricingScheme
    entity: component
    project: Aeroclub Services
    description: Сервис предназначен для работы с профайлами клиентов и компаний
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=19141735
    technologies:
    links:
      - id: db.pricingscheme
        direction: -->
  services.journeys:
    repository: aeroclub.services.journeys
    title: Journeys
    entity: component
    template: Удалить
    project: Aeroclub Services
    description: Поиск командировок с использованием Lucene-индексера
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Journeys
    technologies:
    links:
      - id: backgroundservices.indexer
        direction: --
  services.ordersws:
    repository: aeroclub.services.ordersws
    title: OrdersWS
    entity: component
    project: Aeroclub Services
    description: Создание и обновление услуг, черновиков; добавление в услуги доп. данных, документов, профилей путешественников и т.д.
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Orders
    technologies:
    links:
      - id: db.cabinet
        direction: --
  services.profiles:
    repository: aeroclub.services.profiles
    title: Profiles
    entity: component
    project: Aeroclub Services
    description: REST сервис предназначен для работы с профайлами пользователей
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=19141795
    technologies:
    links:
      - id: db.profiles
        direction: --
  services.propertyfx:
    repository: aeroclub.services.propertyfx
    title: PropertyFx
    entity: component
    project: Aeroclub Services
    description: Работа с доп. данными в Time и Link
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+CustomPropertyFx
    technologies:
    links:
      - id: db.cabinet
        direction: -->
  services.ticketing:
    repository: aeroclub.services.ticketing
    title: Ticketing
    entity: component
    project: Aeroclub Services
    description: Бронирование, выписка, обновление статусов - ЖД и Авиабилеты, через WSCommon
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Ticketing
    technologies:
  services.time_stateengine:
    repository: aeroclub.services.time.stateengine
    title: Time_StateEngine
    entity: component
    project: Aeroclub Services
    description: Получение возможных действий над командировкой. Проверка возможности конкретного действия с командировкой.
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Time.StateEngine
    technologies:
  services.dictionaries:
    repository: aeroclub.platform.dictionaries.service
    title: Dictionaries
    entity: component
    project: Aeroclub Platform
    description:
    url:
    technologies:
    links:
      - id: db.dictdb
        direction: -->
  services.vault:
    repository: aeroclub.vault
    title: Vault (ACIS)
    entity: component
    project: Aeroclub Vault
    description: Он же Aeroclub Card Information Service (ACIS). Используется для валидации и работы с платежными картами. Проверка валидности карты по дате; возможности оплаты выбранным типом карты определенных поставщиков; определение карты, привязанной к профилю компании; добавление карты, работает с DB PosDB
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=19137520
    technologies:
    links:
  services.inappstory:
    repository:
    title: InAppStory
    entity: component
    project: 
    description: Сервис для отображение историй
    url: https://inappstory.ru/
    technologies:
  services.timeApi:
    repository: aeroclub.time.api
    title: TimeApi
    entity: component
    project: Aeroclub Time
    description: Получение данных статистики
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Time.Api
    technologies:
    links:
      - id: db.travelboard
        direction: -->
        title: Получение статистики для виджетов менеджера
      - id: db.cabinet
        direction: -->
        title: Получение настроек виджетов
      - id: services.aeroclubApi
        direction: -->
        title: Получение доступных компаний и форм оплаты
      - id: services.aeroclubApiQuery
        direction: -->
        title: Получение информации из БД Cabinet
      - id: services.dictionaries
        direction: -->
        title: Получение справочников
      - id: services.profiles
        direction: -->
        title: Получение информации профиля
      - id: services.companies
        direction: -->
        title: Получение настроек подписки